IF(@@SERVERNAME='DMDBAPRDSQL04')
BEGIN

USE [master]

ALTER DATABASE [ACFLFBS] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [AmericanRailcarIndustriesInc_MSCRM] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [ANCILE_COLLAB] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [ANCILE_Glossary] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [App_Manager] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [ARICMS] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [ARLIRIX] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [BRC] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [Car_Maintenance] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [CarMaster] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [CLAIMS] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [CommDB] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [Commodity] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [Contracts] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [Customer_Master] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [Ecommerce] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [Emission] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [FLEET_MANAGEMENT] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [Fleetmaint] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [FleetManagementDW] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [FLEETMGMT] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [FM] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [GaugeTable] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [HM201] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [LOTS] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [Mileage] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [model] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [MSCRM_CONFIG] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [NW2007DB] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [Railcar] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [RailcarInvoice] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [ReportServer] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [ReportServerTempDB] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [RM] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [SafetyAssessment] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [SCRIBEINTERNAL] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [SEARCH] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [SECURITY] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [SHARED] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [SharedServices1_DB] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [SharedServices1_Search_DB] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [SharePoint_AdminContent_7cc9074f-a145-43e0-9f63-de530495daaf] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [SharePoint_Config] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [StateTax] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [WSS_Content_MySite] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [WSS_Search_DMDBAPRDMSS02] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;


END