IF(@@SERVERNAME='DMDBAPRDSQL03')
BEGIN

USE [master]

ALTER DATABASE [ariGLdw] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [ariOPSBook_AppDB] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [ariOPSBook_AppDB_AUG] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [ariOPSBook_Interface] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [ariOPSBook_StagingDB] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [attask] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [C8] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [Cognos_Audit_Upgrade] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [DBA] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [enreportsSQL] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [INFOREAM8] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [INFOREAM8_CS] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [ManagementReporter] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [model] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [PPSPlanningService] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [PPSPlanningSystem] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [VIANETDB] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [wfx] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [wfxarch] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;

END