IF(@@SERVERNAME='DMDBAPRDSQL06')
BEGIN

USE [master]

ALTER DATABASE [ACFLFBS] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [App_Manager] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [BRC] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [Car_Maintenance] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [CarMaster] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [Commodity] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [Contracts] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [Customer_Master] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [FleetManagementDW] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [RM] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [RMS] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;
ALTER DATABASE [SHARED] SET PAGE_VERIFY CHECKSUM  WITH NO_WAIT;

END